image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      clear
      lua -v
      luarocks --version
      git --version
      openresty -v
      nginx -v
      # Lista todos os pacotes instalados pelo luarocks
      luarocks list
      luajit -v